<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ARA</name>
   <tag></tag>
   <elementGuidId>bc9d98af-284a-4225-a4e6-0ad127077b5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='searchBoxOld-yDJzsIfi_S5gVgoapx6f']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.searchBoxOld-yDJzsIfi_S5gVgoapx6f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>151bcc0a-f56e-493d-81f8-60c6f43a0a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchBoxOld-yDJzsIfi_S5gVgoapx6f</value>
      <webElementGuid>851b20af-7535-4352-80ad-3d946c3fae59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ARA</value>
      <webElementGuid>8e7b52c9-30c8-4ddc-9480-0ffd0742abfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchBoxOld_46ff6c4a-a070-4334-88e6-10d71c5c8300&quot;)/div[1]/div[@class=&quot;searchBoxOld-uKvVtLzPNdHp38hj3B13&quot;]/div[@class=&quot;searchBoxOld-yDJzsIfi_S5gVgoapx6f&quot;]</value>
      <webElementGuid>0d321c0a-e038-42a0-aed4-ac238095884b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SearchBoxOld_46ff6c4a-a070-4334-88e6-10d71c5c8300']/div/div/div[2]</value>
      <webElementGuid>0d8f48e8-b123-41e4-8bc4-11e176c84c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ürün, kategori veya marka ara'])[1]/following::div[1]</value>
      <webElementGuid>9a6855a4-7ca2-49f1-831b-b599f492fa14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Premium', &quot;'&quot;, 'u')])[1]/following::div[11]</value>
      <webElementGuid>a7d8ff20-c798-4726-a976-87d394dd84e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konum'])[1]/preceding::div[2]</value>
      <webElementGuid>17ab3730-2d4b-46ee-bdae-b04d21a415a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konum seç'])[1]/preceding::div[3]</value>
      <webElementGuid>511bac76-ad45-412c-99b3-1e713f45aa0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ARA']/parent::*</value>
      <webElementGuid>bbf19074-501c-4f55-9dc4-002557633c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>f1cb04e3-d60a-484d-b7f3-e0b0de0f6f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ARA' or . = 'ARA')]</value>
      <webElementGuid>473ba68f-9ec2-4245-8052-2fd8cc454a10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
