<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Giri Yap</name>
   <tag></tag>
   <elementGuidId>11d7d3e8-eda8-4a3c-a60a-ef0ec7107eea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myAccount']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sf-OldMyAccount-d0xCHLV38UCH5cD9mOXq</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6edb1cc9-aa31-4791-865b-5b1530502b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sf-OldMyAccount-d0xCHLV38UCH5cD9mOXq</value>
      <webElementGuid>97721d2d-4864-433f-bc49-4d52e3d76ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Giriş Yap</value>
      <webElementGuid>49d28047-baf1-4e91-b000-f6a96666275f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>5173d36a-09f3-41d1-a7d5-5949d0931c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>62763525-b028-4f20-a7ec-ebe0b37c498a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>account</value>
      <webElementGuid>6a512748-4131-4809-a950-f19b3f835308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Giriş Yap</value>
      <webElementGuid>603c7232-5c42-4f17-bdad-1dd62df1bd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myAccount&quot;)/span[1]/span[@class=&quot;sf-OldMyAccount-d0xCHLV38UCH5cD9mOXq&quot;]</value>
      <webElementGuid>eb3f537a-bd1d-4217-9c81-79cb9cc97b24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myAccount']/span/span</value>
      <webElementGuid>05584398-0b1b-40d0-a3d9-c2c42b39bdc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresinizi veya konum bilgilerinizi seçerek özel hizmetleri görebilirsiniz.'])[1]/following::span[2]</value>
      <webElementGuid>3a3ef8a9-8ca3-481d-aa5d-f740bbdc217f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konumunuzu Belirleyin'])[1]/following::span[2]</value>
      <webElementGuid>1b668e3c-7bfd-4984-8054-657a5379264e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='veya üye ol'])[1]/preceding::span[1]</value>
      <webElementGuid>06a45a6c-aafd-428c-872c-667cf9296104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', &quot;'&quot;, 'la avantajlarını katla!')])[1]/preceding::span[3]</value>
      <webElementGuid>b0298b5e-6e31-41bf-9345-2063a51f174a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Giriş Yap']/parent::*</value>
      <webElementGuid>eb4b3b7d-9919-4d0d-8338-35e614d6c190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>010ded1f-e4eb-4b3d-b4f5-0d61ca1c5f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Giriş Yap' and @href = 'javascript:;' and (text() = 'Giriş Yap' or . = 'Giriş Yap')]</value>
      <webElementGuid>91f57430-31e3-4b1d-8956-240f42b46dbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
