<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Giri Yap</name>
   <tag></tag>
   <elementGuidId>997be6ac-13f2-47d0-83f7-7290dab9eb8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myAccount']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sf-OldMyAccount-d0xCHLV38UCH5cD9mOXq</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4a0fe78b-6d16-480c-8781-ce1b666af9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sf-OldMyAccount-d0xCHLV38UCH5cD9mOXq</value>
      <webElementGuid>e828b353-f33c-43b5-a912-10c4f5dfcd7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Giriş Yap</value>
      <webElementGuid>c4085c64-36bd-4670-bf25-7f41a8aa44e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>714e899f-9bc9-4f53-86d0-75af13402931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>c8e4900c-9288-46a5-ae90-f5174c7efc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>account</value>
      <webElementGuid>f9a1d5a4-821d-4f16-9218-223dc8efae17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Giriş Yap</value>
      <webElementGuid>c85750ca-bc1d-4d02-acd5-8e21addaed08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myAccount&quot;)/span[1]/span[@class=&quot;sf-OldMyAccount-d0xCHLV38UCH5cD9mOXq&quot;]</value>
      <webElementGuid>cb38dce8-4505-4b1a-b237-73161e6339c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myAccount']/span/span</value>
      <webElementGuid>a2668517-80f4-4e99-8dc8-a9d4b7763902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresinizi veya konum bilgilerinizi seçerek özel hizmetleri görebilirsiniz.'])[1]/following::span[2]</value>
      <webElementGuid>9e592257-40c9-4448-bd61-b622c3b37102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konumunuzu Belirleyin'])[1]/following::span[2]</value>
      <webElementGuid>64c64d96-f168-48a3-ae14-3c5ac95adbce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='veya üye ol'])[1]/preceding::span[1]</value>
      <webElementGuid>b10ca6b0-9ccc-46ef-85e9-99fd2b434451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', &quot;'&quot;, 'la avantajlarını katla!')])[1]/preceding::span[3]</value>
      <webElementGuid>ad8767c0-5b0f-4a25-9f72-9263d0f26ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Giriş Yap']/parent::*</value>
      <webElementGuid>de49924e-1e9e-4760-9f5c-56ea8f6d75b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>ae3ffc80-ba76-415d-ac80-c09937068fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Giriş Yap' and @href = 'javascript:;' and (text() = 'Giriş Yap' or . = 'Giriş Yap')]</value>
      <webElementGuid>24b5d12c-af2c-412c-ac2b-d6f61366e7d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
