<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Devam et</name>
   <tag></tag>
   <elementGuidId>ea6e6513-2343-49e2-b998-ffcdf339ea6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSignUpSubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnSignUpSubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d93a14c9-8283-4ee1-b9bc-4d6a5f1a9440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hb-AxmME fyqeGv sqoibpki7sw</value>
      <webElementGuid>9e5ab667-0a5f-4185-836c-7f06ac93f480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kind</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>02b7b502-bdd9-4231-b4d8-2bb0e83213fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>12132545-18a3-44a7-8af3-116d5c443750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSignUpSubmit</value>
      <webElementGuid>25bd8b09-0a7e-4374-8a99-f0e64f2092cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSignUpSubmit</value>
      <webElementGuid>915116ef-dc07-4674-a792-6fefdb7cc804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Devam et</value>
      <webElementGuid>936c6c7c-7118-4e68-a084-702a1d7276c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSignUpSubmit&quot;)</value>
      <webElementGuid>c8459e44-0125-489e-9846-5104fedd37b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSignUpSubmit']</value>
      <webElementGuid>fe270a67-82cf-464e-8aad-bce7fd6f97f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div/div[2]/div[2]/div/div/form/div[2]/button</value>
      <webElementGuid>5a585f13-b750-4422-95aa-268a8594bed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artık cep telefonu numaranızla üye olabilirsiniz.'])[1]/following::button[1]</value>
      <webElementGuid>96524981-5d0c-4c6a-b730-7d018a211bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yeni üye olma yöntemi!'])[1]/following::button[1]</value>
      <webElementGuid>8d12a710-2a7f-4830-8d43-99ee27b692a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aydınlatma Metni'])[1]/preceding::button[1]</value>
      <webElementGuid>b6d55ce9-7f11-4f4d-a4ec-639bf055d8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Üyelik Sözleşmesi'])[1]/preceding::button[1]</value>
      <webElementGuid>b6ec2856-bf16-4711-a596-16349f58df35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Devam et']/parent::*</value>
      <webElementGuid>962e492f-8ae4-482e-aa0e-b82dee0d4c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>d67e02c4-c28b-4e55-97de-862ae45d64c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'btnSignUpSubmit' and @id = 'btnSignUpSubmit' and (text() = 'Devam et' or . = 'Devam et')]</value>
      <webElementGuid>899a82ff-629f-4c7d-bc94-1e7ca6922c62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
