<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Giri yap</name>
   <tag></tag>
   <elementGuidId>72d69e78-4b34-4bfb-b279-5d7efdf9a9a7</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnEmailSelect']
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnLogin</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf3690e5-13d7-479b-b974-668ff2c7a087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hb-AxmME dDtlcs s8zb00vqgro</value>
      <webElementGuid>5efd085c-5ad5-4ac8-b864-d18d3cf97993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kind</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>f4169835-cbfd-4de4-955a-510993a5fa21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d91198c3-8b1a-44b0-885d-f0ed913068c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnLogin</value>
      <webElementGuid>fac67f32-d54c-403b-8d0d-69cca2261164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnLogin</value>
      <webElementGuid>ad54471e-8c75-422f-ac1f-2fd053242854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Giriş yap</value>
      <webElementGuid>bdab5e9f-ed42-40e1-80b0-b71be37bb01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnLogin&quot;)</value>
      <webElementGuid>180d4588-4b6f-48bf-923e-f13fe6d13ccd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnLogin']</value>
      <webElementGuid>2eb346b0-0580-49d9-907f-24905ac70b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div/div[2]/div[2]/div/div/form/button</value>
      <webElementGuid>c979c52b-0241-4c1c-bf66-1360d97b7868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artık cep telefonu numaranızla giriş yapabilirsiniz.'])[1]/following::button[1]</value>
      <webElementGuid>8c4d9ca4-9be1-4963-a2e1-efe41002d020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yeni giriş yöntemi!'])[1]/following::button[1]</value>
      <webElementGuid>c2b3e629-d579-4857-bc5a-4e2dfb47d621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yardıma ihtiyacım var'])[1]/preceding::button[1]</value>
      <webElementGuid>b7da0829-62ea-402b-864e-6fa63aa1904a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sosyal hesap ile giriş yap'])[1]/preceding::button[1]</value>
      <webElementGuid>79abfd5a-0d4c-4fcc-8b7c-c3206c86fa8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>c2cd82f3-4946-418f-b72e-066113155f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'btnLogin' and @id = 'btnLogin' and (text() = 'Giriş yap' or . = 'Giriş yap')]</value>
      <webElementGuid>57fc1da8-1aa1-48f7-8f1d-d8c158132427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnEmailSelect']</value>
      <webElementGuid>a13f2ea8-22cb-4d10-ae70-3ecfa1c41e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmNewLogin']/button</value>
      <webElementGuid>609bd7da-bc45-417b-8db8-3c600e596f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Farklı hesap kullan'])[1]/following::button[1]</value>
      <webElementGuid>e106b520-ffd1-4636-839f-4d22b0e1bfbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Şifremi unuttum'])[1]/preceding::button[1]</value>
      <webElementGuid>d28939e3-9d13-4d25-8c1a-acdeda427781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Giriş yap']/parent::*</value>
      <webElementGuid>7605dcee-a7d3-40db-94b8-7c541b765ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'btnEmailSelect' and @id = 'btnEmailSelect' and (text() = 'Giriş yap' or . = 'Giriş yap')]</value>
      <webElementGuid>04620f7f-e61d-489f-bfaa-1769243790f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
